### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by page1990** [vladimarius/imapy#27]
Greate lib! But there is a problem is when I search for a subject and unseen, there is an error:
`Traceback (most recent call last):
  File "recieve_email.py", line 30, in <module>
    q.subject('what').unseen()
  File "/data/code/cy_devops/lib/python3.5/site-packages/imapy-1.1.1-py3.5.egg/imapy/imap.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/data/code/cy_devops/lib/python3.5/site-packages/imapy-1.1.1-py3.5.egg/imapy/imap.py", line 302, in emails
    result, data = self.imap.uid('SEARCH', *use_query)
  File "/usr/local/python3.5.2/lib/python3.5/imaplib.py", line 863, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/local/python3.5.2/lib/python3.5/imaplib.py", line 1180, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/python3.5.2/lib/python3.5/imaplib.py", line 1011, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: UID command error: BAD [b'UID SEARCH invalid argument']`

**Comment by vladimarius** [comment]
Closing this, please try new v.2 version of the package
